# Generated by Django 3.1.2 on 2020-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField()),
            ],
        ),
    ]
