# Generated by Django 3.1.2 on 2020-10-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20201009_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_created',
            new_name='task_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
