# Generated by Django 3.1.2 on 2020-10-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todo_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(),
        ),
    ]
