# Generated by Django 3.1.2 on 2020-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20201009_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
